import { NextResponse, type NextRequest } from "next/server";
import { getReportStore, isValidToken } from "@/lib/deepdive/store";

// ─── Deep-Dive Report — delivery status poll ─────────────────────────────────
//
// The private delivery page polls this after checkout until its report has been
// generated by the webhook. Returns only status/ready — never the buyer's specs
// or the rendered artifact (that's served by the token-gated delivery page).

export async function GET(req: NextRequest) {
  const token = req.nextUrl.searchParams.get("token") ?? "";
  if (!isValidToken(token)) {
    return NextResponse.json({ status: "invalid", ready: false }, { status: 400 });
  }

  const order = await getReportStore().get(token);
  if (!order) {
    return NextResponse.json({ status: "unknown", ready: false }, { status: 404 });
  }

  return NextResponse.json({
    status: order.status,
    ready: order.status === "fulfilled" && Boolean(order.html),
  });
}
